#! /bin/sh

bspc config border_width 1
bspc config window_gap 5

# Pad for bar
bspc config top_padding 14

# Visual options
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config auto_alternate true
bspc config auto_cancel true

bspc monitor -d I II III IV V VI VII VIII IX X

# Rules

# Processes to start with bspwm
compton &
panel &
sxhkd &

